// <auto-generated />
using Chat;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220925180806_FK2")]
    partial class FK2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Chat.Message", b =>
                {
                    b.Property<int>("_messageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_messageCore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("_userIDFK")
                        .HasColumnType("INTEGER");

                    b.HasKey("_messageID")
                        .HasName("PrimaryKey_messageID");

                    b.HasIndex("_userIDFK");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Chat.User", b =>
                {
                    b.Property<int>("_userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("_userID")
                        .HasName("PrimaryKey_userID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Chat.Message", b =>
                {
                    b.HasOne("Chat.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("_userIDFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat.User", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
